server:
  port: 9003

spring:
  application:
    name: COURSE-APP
  zipkin:
    base-uri: http://127.0.0.1:9411

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    server-url:
#      default-zone: http://localhost:8761/eureka/
#  instance: localhost